services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432 

  server:
    build:
      context: ../server
    depends_on: 
      - db
    command: sh -c "npx prisma generate && npx prisma db push && npx ts-node index.ts"
    ports:
      - 5000:5000
volumes:
  pgdata:
